backend:
  name: git-gateway
  branch: master

media_folder: "img"
display_url: https://tarugo21.netlify.app/

collections:
  - label: Datos
    name: data
    preview: false
    files:
      - label: Entradas
        name: "tickets"
        file: _data/tickets.yml
        fields:
          - label: title
            name: title
            widget: string
          - label: Entradas
            name: tickets
            widget: list
            fields:
              - label: Nombre
                name: name
                widget: string
              - label: Precio
                name: pricing
                widget: string
              - label: Descripción
                name: description
                widget: markdown
              - label: Incluye
                name: includes
                widget: list
                field:
                  label: Texto
                  name: text
                  widget: markdown
              - label: Envío
                name: delivery
                widget: object
                fields:
                  - label: Fecha
                    name: date
                    widget: string
                  - label: Dirección
                    name: address
                    widget: string
              - label: Complementos
                name: complements
                widget: boolean
              - label: Stock
                name: stock
                widget: number
                required: false

      - label: Agenda
        name: calendar
        file: _data/home/calendar.yml
        fields:
          - label: Título
            name: title
            widget: string
          - label: Intro
            name: intro
            widget: markdown
          - label: Días
            name: days
            widget: list
            fields:
              - label: Día
                name: day
                widget: string
              - label: Eventos
                name: events
                widget: list
                fields:
                  - label: Título
                    name: title
                    widget: string
                  - label: Hora
                    name: time
                    widget: string
                  - label: Descripción
                    name: details
                    widget: markdown
                    required: false

      - label: Speakers
        name: speakers
        file: _data/home/speakers.yml
        fields:
          - label: Título
            name: title
            widget: string
          - label: Intro
            name: intro
            widget: markdown
          - label: Speakers
            name: speakers
            widget: list
            fields:
              - label: Nombre
                name: name
                widget: string
              - label: Empresa
                name: company
                widget: string
              - label: Cargo
                name: position
                widget: string
              - label: Imagen
                name: image
                widget: image
                allow_multiple: false
                media_folder: /img/speakers
              - label: Enlaces
                name: links
                widget: list
                fields:
                  - label: Texto
                    name: text
                    widget: string
                  - label: Tipo
                    name: type
                    widget: select
                    options: ["twitter", "linkedin", "web"]
                  - label: Url
                    name: url
                    widget: string
              - label: Biografía
                name: bio
                widget: markdown
                required: false

      - label: Partners
        name: partners
        file: _data/home/partners.yml
        fields:
          - label: Título
            name: title
            widget: string
          - label: Intro
            name: intro
            widget: markdown
          - label: Partner principal
            name: main
            widget: object
            fields:
              - label: Alt
                name: alt
                widget: string
              - label: Imagen
                name: img
                widget: image
                allow_multiple: false
                media_folder: /img/partners
              - label: Url
                name: url
                widget: string
              - label: Texto
                name: text
                widget: markdown
          - label: Partners secundarios
            name: partners
            widget: list
            fields:
              - label: Alt
                name: alt
                widget: string
              - label: Imagen
                name: img
                widget: image
                allow_multiple: false
                media_folder: /img/partners
              - label: Url
                name: url
                widget: string
              - label: Texto
                name: text
                widget: markdown
          - label: Patrocinadores
            name: patrons
            widget: list
            fields:
              - label: Alt
                name: alt
                widget: string
              - label: Imagen
                name: img
                widget: image
                allow_multiple: false
                media_folder: /img/partners
              - label: Url
                name: url
                widget: string
          - label: Únete
            name: join
            widget: object
            fields:
              - label: Título
                name: title
                widget: string
              - label: Texto
                name: content
                widget: markdown
