backend:
  name: git-gateway
  branch: master

media_folder: "img"
collections:
  - label: Datos
    name: data
    files:
      - label: Entradas
        name: "tickets"
        file: _data/tickets.yml
        fields:
          - label: title
            name: title
            widget: string
