backend:
  name: git-gateway
  branch: master

media_folder: "img"

collections:
  - label: Agenda
    name: calendar
    file: _data/calendar.yml
    fields:
      - label: Eventos
        name: events
        widget: list
        fields:
          - label: Título
            name: title
            widget: string
          - label: Día
            name: time
            widget: datetime
          - label: Texto
            name: text
            widget: markdown

  - label: Datos
    name: data
    files:
      - label: Entradas
        name: "tickets"
        file: _data/tickets.yml
        fields:
          - label: title
            name: title
            widget: string
