name: Publish

on:
  push:
    branches: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: v1.x

      - name: Run lume
        run: |
          deno run --unstable -A https://deno.land/x/lume/cli.js --location=https://tarugoconf.github.io/tarugo21/
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EVENT_ID: ${{ secrets.EVENT_ID }}

